
#include "M6502Asm.h"

namespace M6502 {
namespace Asm {

const struct metadata instructions[256] =
{
    {2, 7, IMP, "BRK"},
    {2, 6, INX, "ORA"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 8, INX, "SLO", unofficial : 1},
    {2, 3, ZPG, "NOP", unofficial : 1},
    {2, 3, ZPG, "ORA"},
    {2, 5, ZPG, "ASL"},
    {2, 5, ZPG, "SLO", unofficial : 1},
    {1, 3, IMP, "PHP"},
    {2, 2, IMM, "ORA"},
    {1, 2, ACC, "ASL"},
    {2, 2, IMM, "AAC", unofficial : 1},
    {3, 4, ABS, "NOP", unofficial : 1},
    {3, 4, ABS, "ORA"},
    {3, 6, ABS, "ASL"},
    {3, 6, ABS, "SLO", unofficial : 1},
    {2, 2, REL, "BPL"},
    {2, 5, INY, "ORA"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 8, INY, "SLO", unofficial : 1},
    {2, 4, ZPX, "NOP", unofficial : 1},
    {2, 4, ZPX, "ORA"},
    {2, 6, ZPX, "ASL"},
    {2, 6, ZPX, "SLO", unofficial : 1},
    {1, 2, IMP, "CLC"},
    {3, 4, ABY, "ORA"},
    {1, 2, IMP, "NOP", unofficial : 1},
    {3, 7, ABY, "SLO", unofficial : 1},
    {3, 4, ABX, "NOP", unofficial : 1},
    {3, 4, ABX, "ORA"},
    {3, 7, ABX, "ASL"},
    {3, 7, ABX, "SLO", unofficial : 1},
    {3, 6, ABS, "JSR"},
    {2, 6, INX, "AND"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 8, INX, "RLA", unofficial : 1},
    {2, 3, ZPG, "BIT"},
    {2, 3, ZPG, "AND"},
    {2, 5, ZPG, "ROL"},
    {2, 5, ZPG, "RLA", unofficial : 1},
    {1, 4, IMP, "PLP"},
    {2, 2, IMM, "AND"},
    {1, 2, ACC, "ROL"},
    {2, 2, IMM, "AAC", unofficial : 1},
    {3, 4, ABS, "BIT"},
    {3, 4, ABS, "AND"},
    {3, 6, ABS, "ROL"},
    {3, 6, ABS, "RLA", unofficial : 1},
    {2, 2, REL, "BMI"},
    {2, 5, INY, "AND"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 8, INY, "RLA", unofficial : 1},
    {2, 4, ZPX, "NOP", unofficial : 1},
    {2, 4, ZPX, "AND"},
    {2, 6, ZPX, "ROL"},
    {2, 6, ZPX, "RLA", unofficial : 1},
    {1, 2, IMP, "SEC"},
    {3, 4, ABY, "AND"},
    {1, 2, IMP, "NOP", unofficial : 1},
    {3, 7, ABY, "RLA", unofficial : 1},
    {3, 4, ABX, "NOP", unofficial : 1},
    {3, 4, ABX, "AND"},
    {3, 7, ABX, "ROL"},
    {3, 7, ABX, "RLA", unofficial : 1},
    {1, 6, IMP, "RTI"},
    {2, 6, INX, "EOR"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 8, INX, "SRE", unofficial : 1},
    {2, 3, ZPG, "NOP", unofficial : 1},
    {2, 3, ZPG, "EOR"},
    {2, 5, ZPG, "LSR"},
    {2, 5, ZPG, "SRE", unofficial : 1},
    {1, 3, IMP, "PHA"},
    {2, 2, IMM, "EOR"},
    {1, 2, ACC, "LSR"},
    {2, 2, IMM, "ASR", unofficial : 1},
    {3, 3, ABS, "JMP"},
    {3, 4, ABS, "EOR"},
    {3, 6, ABS, "LSR"},
    {3, 6, ABS, "SRE", unofficial : 1},
    {2, 2, REL, "BVC"},
    {2, 5, INY, "EOR"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 8, INY, "SRE", unofficial : 1},
    {2, 4, ZPX, "NOP", unofficial : 1},
    {2, 4, ZPX, "EOR"},
    {2, 6, ZPX, "LSR"},
    {2, 6, ZPX, "SRE", unofficial : 1},
    {1, 2, IMP, "CLI"},
    {3, 4, ABY, "EOR"},
    {1, 2, IMP, "NOP", unofficial : 1},
    {3, 7, ABY, "SRE", unofficial : 1},
    {3, 4, ABX, "NOP", unofficial : 1},
    {3, 4, ABX, "EOR"},
    {3, 7, ABX, "LSR"},
    {3, 7, ABX, "SRE", unofficial : 1},
    {1, 6, IMP, "RTS"},
    {2, 6, INX, "ADC"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 8, INX, "RRA", unofficial : 1},
    {2, 3, ZPG, "NOP", unofficial : 1},
    {2, 3, ZPG, "ADC"},
    {2, 5, ZPG, "ROR"},
    {2, 5, ZPG, "RRA", unofficial : 1},
    {1, 4, IMP, "PLA"},
    {2, 2, IMM, "ADC"},
    {1, 2, ACC, "ROR"},
    {2, 2, IMM, "ARR", unofficial : 1},
    {3, 5, IND, "JMP"},
    {3, 4, ABS, "ADC"},
    {3, 6, ABS, "ROR"},
    {3, 6, ABS, "RRA", unofficial : 1},
    {2, 2, REL, "BVS"},
    {2, 5, INY, "ADC"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 8, INY, "RRA", unofficial : 1},
    {2, 4, ZPX, "NOP", unofficial : 1},
    {2, 4, ZPX, "ADC"},
    {2, 6, ZPX, "ROR"},
    {2, 6, ZPX, "RRA", unofficial : 1},
    {1, 2, IMP, "SEI"},
    {3, 4, ABY, "ADC"},
    {1, 2, IMP, "NOP", unofficial : 1},
    {3, 7, ABY, "RRA", unofficial : 1},
    {3, 4, ABX, "NOP", unofficial : 1},
    {3, 4, ABX, "ADC"},
    {3, 7, ABX, "ROR"},
    {3, 7, ABX, "RRA", unofficial : 1},
    {2, 2, IMM, "NOP", unofficial : 1},
    {2, 6, INX, "STA"},
    {2, 2, IMM, "NOP", unofficial : 1},
    {2, 6, INX, "SAX", unofficial : 1},
    {2, 3, ZPG, "STY"},
    {2, 3, ZPG, "STA"},
    {2, 3, ZPG, "STX"},
    {2, 3, ZPG, "SAX", unofficial : 1},
    {1, 2, IMP, "DEY"},
    {2, 2, IMM, "NOP", unofficial : 1},
    {1, 2, IMP, "TXA"},
    {2, 2, IMM, "ANE", unofficial : 1},
    {3, 4, ABS, "STY"},
    {3, 4, ABS, "STA"},
    {3, 4, ABS, "STX"},
    {3, 4, ABS, "SAX", unofficial : 1},
    {2, 2, REL, "BCC"},
    {2, 6, INY, "STA"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 5, INY, "SHA", unofficial : 1},
    {2, 4, ZPX, "STY"},
    {2, 4, ZPX, "STA"},
    {2, 4, ZPY, "STX"},
    {2, 4, ZPY, "SAX", unofficial : 1},
    {1, 2, IMP, "TYA"},
    {3, 5, ABY, "STA"},
    {1, 2, IMP, "TXS"},
    {3, 4, ABY, "SHS", unofficial : 1},
    {3, 4, ABX, "SHY", unofficial : 1},
    {3, 5, ABX, "STA"},
    {3, 4, ABY, "SHX", unofficial : 1},
    {3, 4, ABY, "SHA", unofficial : 1},
    {2, 2, IMM, "LDY"},
    {2, 6, INX, "LDA"},
    {2, 2, IMM, "LDX"},
    {2, 6, INX, "LAX", unofficial : 1},
    {2, 3, ZPG, "LDY"},
    {2, 3, ZPG, "LDA"},
    {2, 3, ZPG, "LDX"},
    {2, 3, ZPG, "LAX", unofficial : 1},
    {1, 2, IMP, "TAY"},
    {2, 2, IMM, "LDA"},
    {1, 2, IMP, "TAX"},
    {2, 2, IMM, "ATX", unofficial : 1},
    {3, 4, ABS, "LDY"},
    {3, 4, ABS, "LDA"},
    {3, 4, ABS, "LDX"},
    {3, 4, ABS, "LAX", unofficial : 1},
    {2, 2, REL, "BCS"},
    {2, 5, INY, "LDA"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 5, INY, "LAX", unofficial : 1},
    {2, 4, ZPX, "LDY"},
    {2, 4, ZPX, "LDA"},
    {2, 4, ZPY, "LDX"},
    {2, 4, ZPY, "LAX", unofficial : 1},
    {1, 2, IMP, "CLV"},
    {3, 4, ABY, "LDA"},
    {1, 2, IMP, "TSX"},
    {3, 4, ABY, "LAS", unofficial : 1},
    {3, 4, ABX, "LDY"},
    {3, 4, ABX, "LDA"},
    {3, 4, ABY, "LDX"},
    {3, 4, ABY, "LAX", unofficial : 1},
    {2, 2, IMM, "CPY"},
    {2, 6, INX, "CMP"},
    {2, 2, IMM, "NOP", unofficial : 1},
    {2, 8, INX, "DCP", unofficial : 1},
    {2, 3, ZPG, "CPY"},
    {2, 3, ZPG, "CMP"},
    {2, 5, ZPG, "DEC"},
    {2, 5, ZPG, "DCP", unofficial : 1},
    {1, 2, IMP, "INY"},
    {2, 2, IMM, "CMP"},
    {1, 2, IMP, "DEX"},
    {2, 2, IMM, "AXS", unofficial : 1},
    {3, 4, ABS, "CPY"},
    {3, 4, ABS, "CMP"},
    {3, 6, ABS, "DEC"},
    {3, 6, ABS, "DCP", unofficial : 1},
    {2, 2, REL, "BNE"},
    {2, 5, INY, "CMP"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 8, INY, "DCP", unofficial : 1},
    {2, 4, ZPX, "NOP", unofficial : 1},
    {2, 4, ZPX, "CMP"},
    {2, 6, ZPX, "DEC"},
    {2, 6, ZPX, "DCP", unofficial : 1},
    {1, 2, IMP, "CLD"},
    {3, 4, ABY, "CMP"},
    {1, 2, IMP, "NOP", unofficial : 1},
    {3, 7, ABY, "DCP", unofficial : 1},
    {3, 4, ABX, "NOP", unofficial : 1},
    {3, 4, ABX, "CMP"},
    {3, 7, ABX, "DEC"},
    {3, 7, ABX, "DCP", unofficial : 1},
    {2, 2, IMM, "CPX"},
    {2, 6, INX, "SBC"},
    {2, 2, IMM, "NOP", unofficial : 1},
    {2, 8, INX, "ISB", unofficial : 1},
    {2, 3, ZPG, "CPX"},
    {2, 3, ZPG, "SBC"},
    {2, 5, ZPG, "INC"},
    {2, 5, ZPG, "ISB", unofficial : 1},
    {1, 2, IMP, "INX"},
    {2, 2, IMM, "SBC"},
    {1, 2, IMP, "NOP"},
    {2, 2, IMM, "SBC", unofficial : 1},
    {3, 4, ABS, "CPX"},
    {3, 4, ABS, "SBC"},
    {3, 6, ABS, "INC"},
    {3, 6, ABS, "ISB", unofficial : 1},
    {2, 2, REL, "BEQ"},
    {2, 5, INY, "SBC"},
    {1, 0, IMP, "???", unofficial: 1, jam: 1},
    {2, 8, INY, "ISB", unofficial : 1},
    {2, 4, ZPX, "NOP", unofficial : 1},
    {2, 4, ZPX, "SBC"},
    {2, 6, ZPX, "INC"},
    {2, 6, ZPX, "ISB", unofficial : 1},
    {1, 2, IMP, "SED"},
    {3, 4, ABY, "SBC"},
    {1, 2, IMP, "NOP", unofficial : 1},
    {3, 7, ABY, "ISB", unofficial : 1},
    {3, 4, ABX, "NOP", unofficial : 1},
    {3, 4, ABX, "SBC"},
    {3, 7, ABX, "INC"},
    {3, 7, ABX, "ISB", unofficial : 1},
};

};
};
